[package]
name = "resolve_collision"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
ncollide3d = "0.33.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"
stl_io = "0.7.0"
